
data Eval = Eval ** (V^n).(E<=Eval)

{-==================


* ... / Eval / ...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...


* ... / x / ...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...


* ... / x / ...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...


* ... / x / ...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...


* ... / x / ...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...


* ... / x / ...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...


* ... / x / ...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
* ... / x / ...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
** ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...
++ ... / x / ...
...
...
...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
... / x / x / x / x / x / x / x / x / ...
...
...
...
...


===================-}
